name: Run Unit Tests

on:
  push:
    branches: [ main]
  pull_request:
    branches: [ main]

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ['3.13']
    
    runs-on: ${{ matrix.os }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: Display Python version
      run: python -c "import sys; print(f'Python version: {sys.version}')"
      
    - name: Run unit tests
      run: python3 -m unittest test_square.py
      run: python3 -m unittest test_triangle.py
      run: python3 -m unittest test_rectangle.py
      run: python3 -m unittest test_circle.py  